### ISSUE TITLE
PlatformIO Version not up to date

### ISSUE THREAD

**Issue by Nailik** [LennartHennigs/ESPTelnet#15]
The Version of this library on PlatformIO https://platformio.org/lib/show/7183/ESP%20Telnet seems to be not up to date.
It still contains i`f (WiFi.status() == WL_CONNECTED || WiFi.softAPIP().isSet()) {` that  was removed in 1.2.1 but it says it is version 1.2.1.

Maybe you can somehow trigger a reload from PlatformIO or release a dummy 1.2.2 version?

**Comment by LennartHennigs** [comment]
Hey,
I updated the version. 
The code that included the isSet() was available here on Github but not released. 
I usually wait a few days to see if people have comments / corrections before I do a real release of Arduino IDE & platform.io.
