### ISSUE TITLE
Feature request: change port, disconnect client

### ISSUE THREAD

**Issue by modest1981** [LennartHennigs/ESPTelnet#18]
Hello
Is there any way I can change the default listening port (23)?

Is there any way I can disconnect the client?

**Comment by LennartHennigs** [comment]
Hey,
Not yet. 

For now you could change the port in the .h file in line 47. and you could add yourself a function where you call client.stop() as in line 75.  

But valid points, will add them on my todo list on things to update. 

Cheers
l.

**Comment by modest1981** [comment]
Thanks for the help but I can't understand the second part. Could you explain more in detail?

**Comment by LennartHennigs** [comment]
Hey, just pushed a change.  
You can now define a custom port via the `begin(uint16_t port)` function. 
And added `clientDisconnect()`.  I use them  one in the standard example. 
It is not yet part of a full release.

**Comment by LennartHennigs** [comment]
This is now part of 1.3.0

**Comment by modest1981** [comment]
Great. Thank you.
