### ISSUE TITLE
Support for ESP32 should be added

### ISSUE THREAD

**Issue by mrdc** [LennartHennigs/ESPTelnet#2]
Hello,

Would be nice to add ESP32 support :)

BTW Does your library can forwards all info from the serial including verbose output?

**Comment by LennartHennigs** [comment]
Hey, I finally updated the class. 
ESP32 support should work now. I'll test it tomorrow and then release it if it does.

To your second question I cannot capture Serial.println() output - a good explanation is given [here](https://forum.arduino.cc/index.php?topic=588988.0). But I can use serial input to send to the telnet, see the example, but this is most likely not what you are looking for. You'll have to replace your Serial.print with telnet.print.

**Comment by LennartHennigs** [comment]
Tested it and tweaked it a bit. 
Now it runs on a M5Stack without problems.
