### ISSUE TITLE
AP Support for ESP32

### ISSUE THREAD

**Issue by UdayChaduvula** [LennartHennigs/ESPTelnet#23]
Hi when I see the examples code WiFi manager, it is telling that AP mode is not yet supported for ESP 32. Is it supported now for ESP 32?

**Comment by LennartHennigs** [comment]
This is an issue with and a question for the WifiManager. 
But I think there is a beta for the esp32. Please check their repository. Alternatively, you can use the  AutoConnect with the esp32.
