### ISSUE TITLE
Why "LF" and not "CR" in Telnet console for "return" and "local echo" on?

### ISSUE THREAD

**Issue by sosojaja** [LennartHennigs/ESPTelnet#33]
Hi LennartHennings,

ahead very thank you for this tool and the new "stream" example what get an answert my problem.

My problem was that I could not insert something im my Telnet console for which I used "Tera Term". It could by that other terminal programs didn't have or shows this problem.
1. Without "local echo" I could not see any input in the telent console.
2. After input some characters and close them with "return", nothing happend out of I saw my entries in the "serial console" from arduino. If I insert new characters they overwrite the old one in the serial console but the "return" didn't get any action.

Sorry for this question or perhaps ignorance. I'm not a profi software developer, but I use "Tera Term" for "telnet", "ssh" and "uart" at my work. There I have this problem normally not. Only at "AT" command consoles there I must shwitch on the "local echo" too.
To see an action after insert "Return" I must configure "LF" instead of "CR" at "Tera Term" "Terminal-Settings" in "Transmit" and "send" for "New row". This is no k.o. criterion but I find this complicated the using very much.
Perhapse you will change something at this tool and it will not be a bigger doning, could you change this? But this will be only nice to have, not more.

Best regards,
sosojaja

**Comment by LennartHennigs** [comment]
Hey @sosojaja,
thanks for the feedback.

I am not sure I can do much about activating local echo.
But I can take a look at the CR vs LF problem.
I need to replicate your problem, as I use a Mac and different software.
I will come back to you.

**Comment by DadelNet** [comment]
Hi @sosojaja 

fyi, in PuTTY, there is a setting in the terminal emulator setting to force an "Implicit CR after LF" and an "Implicit LF after CR" and that works fine. Is that not available in Tera Term ?

**Comment by sosojaja** [comment]
Hi, thank you for you information, TeraTerm has this function too, but all other things need another setting and I'm must switch each time. But at the moment I found a solution to load different settings with a short cut. But I asked me why all other telnet connections need this settings not?

**Comment by LennartHennigs** [comment]
Hey, I tried now a few other Terminal  and spend some time reading on the telnet protocol and in the end it boils down to how you configure your terminal client. As @DadelNet said, enable CRLF, and enable local echo. 
I also spent some time looking at Telnet [IAC](http://pcmicro.com/netfoss/telnet.html)s and looking if we can negotiate some settings with the Terminal client but this feels like a stretch to me.
I am considering adding a mechanism for detecting and sending IACs in the future. But for now you need to update the settings manually.
