### ISSUE TITLE
Build error: WiFiClient::status() not defined on ESP32

### ISSUE THREAD

**Issue by AFontaine79** [LennartHennigs/ESPTelnet#5]
The WiFiClient class does not appear to be cross-compatible between ESP8266 and ESP32.  Annoying, yes, I know.
Anyway... see here:
For the ESP8266, the declaration of status() method is on line 55 of [WiFiClient.h](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/WiFiClient.h).
For the ESP32, [WiFiClient.h](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiClient.h) has no status() method.
I'm just going to modify the code to work around this for now.

**Comment by LennartHennigs** [comment]
Hey, I think there is a status() method for the ESP32. Its used in their example:

https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiClient/WiFiClient.ino

(...and my libs and its example compiles and runs on my M5Stack Core)

**Comment by AFontaine79** [comment]
You are correct.  You actually fixed this issue in commit 830fd75 on Feb 3rd.  My guess is that I somehow grabbed the wrong library version in PlatformIO, which has its own library manager.  Like you said, it builds fine in the Arduino IDE.  I went back and asked PlatformIO to revert my changes to ESPTelnet, and now it looks the same as here.  I am closing this issue.
