### ISSUE TITLE
Expose TCPClient 

### ISSUE THREAD

**Issue by rcmontrose** [LennartHennigs/ESPTelnet#57]
I would like to suggest an enhancement to declare the TCPClient public (it's currently protected) or provide an accessor method. I need direct access to the TCPClient to implement a custom print for the Telnet client (it expands newlines to return, newline). I'm currently moving the declaration in ESPTelnetBase.h for the client from protected to public.

**Comment by LennartHennigs** [comment]
Hey @rcmontrose,
the base class in the branch [57-expose-tcpclient](https://github.com/LennartHennigs/ESPTelnet/tree/57-expose-tcpclient) now has a `public getClient()`function.
Please give it a try.
