### ISSUE TITLE
remove the `ESP8266WebServer.h` inclusion 

### ISSUE THREAD

**Issue by LennartHennigs** [LennartHennigs/ESPTelnet#65]
> can you please remove the `ESP8266WebServer.h` inclusion if it's not doing anything useful? It's conflicting with the https://github.com/me-no-dev/ESPAsyncWebServer library.

Taken from #64.

**Comment by LennartHennigs** [comment]
fixed in the branch. will merge soon.

**Comment by Sylvio84** [comment]
Hello,
Yes ESP8266WebServer seems not to be used.
I also have this problem, thanks for the upcoming correction.

**Comment by LennartHennigs** [comment]
Hey @Sylvio84, hey @ DRSDavidSoft,
this is now part of 2.2.2.
Cheers
