### ISSUE TITLE
webserver.h conflicts with ESPASYNC

### ISSUE THREAD

**Issue by MichielfromNL** [LennartHennigs/ESPTelnet#8]
In the ESP2 include, Webserver.h is not really needed
It conflicts with definitions if ESPAsyncwebserver is used in which case the sketch doesn't compile

#if defined(ARDUINO_ARCH_ESP32)  #include &lt;WiFi.h&gt;  #include &lt;WebServer.h&gt;#elif defined(ARDUINO_ARCH_ESP8266)

replace by:

#if defined(ARDUINO_ARCH_ESP32)  #include &lt;WiFi.h&gt; &gt;#elif defined(ARDUINO_ARCH_ESP8266)

**Comment by LennartHennigs** [comment]
Hey,
Thanks for pointing this out. Will fix it. 
Cheers.
